version: '3.8'

services:

  db:
    image: postgres:16-alpine
    container_name: task-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile 
    container_name: task-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tasks
      DB_PORT: 5432
      PORT: 8080
    ports:
      - "8080:8080"

  
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    container_name: task-frontend
    restart: always
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    ports:
      - "80:80"

volumes:
  postgres_data: